### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by yunhaoli1995** [KaijuML/data-to-text-hierarchical#19]
Hi, how long does it take to train a model? It took me about four days to walk 100000 steps. Besides, have you ever tried to use transformer as decoder?

**Comment by KaijuML** [comment]
Hi,

Indeed, you should not go through the entire 100,000 steps (this number is there as a safeguard so that the code does'nt just keep on running). In practice, I think 15,000 steps are close to enough, so it should take around 12h at most. 

What I advise is: train up to 20,000 steps, save intermediate checkpoints (e.g. every 500 steps), and evaluate final checkpoints to select the best. Select the best given your metric of choice (BLEU can work, although RG is probably better).

I have just released a pytorch RG metric, you can follow instructions at: https://github.com/KaijuML/rotowire-rg-metric

I am closing this issue for now, do not hesitate to re open if needed. Note that I have opened [Discussions](https://github.com/KaijuML/data-to-text-hierarchical/discussions) for this repo, so feel free to ask questions there also if they are not issue-related.

Cheers,
