### ISSUE TITLE
About GPU memory while training.

### ISSUE THREAD

**Issue by JaeShinJun** [KaijuML/data-to-text-hierarchical#7]
I have issue while training your model.

As the training process progresses, gpu memory usage increases.
Although there is an upper limit, there is a problem in determining the appropriate batch size.
I 'm currently thinking there might be gpu memory leak in somewhere and trying to find it.

Any ideas? Weren't you have same problem with me? Thanks.

**Comment by KaijuML** [comment]
Hi,

This should be expected, because of how pytorch allocates memory.
Each time a tensor is moved to your gpu device, pytorch will choose between two options:
- allocating more memory (and you will see an increase in memory usage when monitoring with nvidia-smi for instance)
- reusing some previously allocated memory which is no longer in use

However, pytorch never on its own free the memory which is no longer in use. This is why, batch after batch the memory usage can only increase, for at each bigger batch, pytorch grabs more memory, but never releases it for a smaller batch. This also why there is an upper limit, when the biggest batch has been processed.

There is no way to know what that maximum will be except either running the first epoch, or computing by hand the size of the tensors created when processing the biggest batch.

Let me know,
Cheers

**Comment by JaeShinJun** [comment]
Thanks for answering! Your answer helps me a lot.

I just have one more question. 
What is the most significant thing which differ the gpu memory usage between batches?

Thank you for answering again!

**Comment by JaeShinJun** [comment]
I have resolved this issue by control vocab size!

Your works helps me a lot! Thanks.
